[32mINFO    [0m test_异常自动截图.py:test_异常自动截图.py:33 用例发生异常了